language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.7"
  - "3.8"

before_install:
  - pip install --upgrade setuptools pip
  - pip install --upgrade pylint pytest pytest-pylint pytest-runner
install:
  - pip install termcolor
  - pip install hypothesis python-Levenshtein
  - python setup.py develop
script:
  - python -m pytest  # Run the tests without IPython.
  - pip install ipython
  - python -m pytest  # Now run the tests with IPython.
  - pylint fire --ignore=test_components_py3.py,parser_fuzz_test.py,console
  - if [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then
      pip install pytype;
    fi
  # Run type-checking, excluding files that define or use py3 features in py2.
  - if [[ $TRAVIS_PYTHON_VERSION == 2.7 ]]; then
      pytype -x
        fire/fire_test.py
        fire/inspectutils_test.py
        fire/test_components_py3.py;
    elif [[ $TRAVIS_PYTHON_VERSION != 3.4 ]]; then
      pytype;
    fi
